### ISSUE TITLE
How do I actually connect to DynamoDB?

### ISSUE THREAD

**Issue by damianesteban** [shiftcode/dynamo-easy#146]
This library is very impressive, but I have a question (maybe I'm missing something):

How do I actually connect to a DynamoDB instance on AWS. In the `DynamoRx` class for example I see an option for `awsRegion` but what about the other required parameters? Is it possible to use this client with a local dynamodb instance?

Thank you.

**Comment by michaelwittwer** [comment]
@damianesteban thanks for getting in touch. Dynamo-Easy is basically a wrapper around the DynamoDB api from aws-sdk. This means you got all the same configuration possibilities as if you would use DynamoDB directly.

The DynamoDB will load the configuration from global aws config. So the easiest is to update the config to your needs, before a DynamoDB instance is created. (Because the config of the service instance is a snapshot of the global config at the time of initialization - see
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/global-config-object.html for more info)
`
import * as AWS from 'aws-sdk/global'

AWS.config.update({dynamodb: {endpoint: 'localEndpoint'}})
`

If you have the need to have some configuration properties for a single instance of DynamoDb you need to get a hold of that instance and update the config.

`
import { DynamoStore } from '@shiftcoders/dynamo-easy'

const myStore = new DynamoStore(OrderLinkedForm)
myStore.dynamoDb.config.endpoint = 'myEndpoint'

// do your request which should go the new configured endpoint
`

**Comment by michaelwittwer** [comment]
@damianesteban closing for now, feel free to reopen if you have more questions

**Comment by damianesteban** [comment]
Excellent. Thank you for the explanation.
