### ISSUE TITLE
Question: @PartitionKey() - use mapper to create auto generate?

### ISSUE THREAD

**Issue by VuongN** [shiftcode/dynamo-easy#244]
Thank you again for a great library. I'm trying to convert from [@aws/dynamodb-data-mapper-js](https://github.com/awslabs/dynamodb-data-mapper-js). Just a quick question:

For PartitionKey, I'd like to auto generate a [nanoid](https://github.com/ai/nanoid), would I use a mapper here?

Possibly related: https://github.com/shiftcode/dynamo-easy/issues/91

Thanks.
-V.

**Comment by michaelwittwer** [comment]
Hi @VuongN 
Happy to see you here.

A custom mapper only helps if an actual value is defined on the model when running through toDb (because we call `const propertyNames = <Array<keyof T>>Object.getOwnPropertyNames(item) || []`). For now, you could initialize the id field with a marker value and then replace it with the generated value in your custom mapper if the value matches the marker value.

```
export const NanoIdMapper: MapperForType<string, StringAttribute> = {
  fromDb: attributeValue => attributeValue.S,
  toDb: propertyValue => {
    if (propertyValue === NANO_ID_MARKER) {
      return { S: nanoId.generate() }
    } else {
      return { S: propertyValue }
    }
  }
}
```

and your model definition

```
@Model()
export class ModelWithNanoId {
  @PartitionKey()
  @Property({ mapper: NanoIdMapper })
  id: string
}
```

whenever you are trying to put a new item make sure to initialize the id field with the marker value.

We are planning to implement a new feature to generate a default value ((no roadmap yet) when putting a new item to DynamoDb. This should then cover your use-case.

**Comment by VuongN** [comment]
I appreciated the reply. I went ahead and just manually created the `id` value on put. Definitely look forward to that generate default feature though.

**Comment by simonmumenthaler** [comment]
Hi @VuongN 
We made the prerelease [6.0.0-pr91.1](https://www.npmjs.com/package/@shiftcoders/dynamo-easy/v/6.0.0-pr91.1) with this `defaultValueProvider` feature.

Would be great if you could test this out and give some feedback.

The usage looks like this:
```
@Model()
export class ModelWithDefaultValue {
  @PartitionKey()
  @Property({ defaultValueProvider: () => nanoId() })
  id: string
}
```

**Comment by VuongN** [comment]
On a different project at the moment but will definitely take a look later and will give any feedback if there's any cause for concern. I'd imagine, since it looks straightforward enough, pretty sure everything will work out perfectly. Thanks for the great work and effort here!
