### ISSUE TITLE
Question: Docs/Change Log?

### ISSUE THREAD

**Issue by VuongN** [shiftcode/dynamo-easy#254]
- It appears that docs are quite outdated, some crucial docs aren't there, I found stuff from reading docs but I feel that others might benefits from an updated docs. I would love to contribute, but haven't figure out the "contributor" docs :P 
- New version (v5.4.0) was released recently but I couldn't find the change log. Could you point me toward the change logs? I was reading through the commits, but was worried that I missed something.
Thanks!
-V.

**Comment by michaelwittwer** [comment]
Thanks for reaching out @VuongN 

**Docs**
We are more than happy to accept contributions to the documentation. Right now we are not ready to accept contributions to the docs in a nice way. Because we use gitbooks for the docs, I would have to add you to the team there and upgrade the plan, which is not really an option right now.
We would love to have an other way of doc, which lives closer to the code. To also be able to create PRs with code & doc updates in one shot.
For now I could kick out @simonmumenthaler as a writer and invite you, so you could contribute your changes as a draft, if this is an option for you, after the changes I would remove you from gitbook again. (there are no fees for you)
One option could also be to create a new organization on gitbook and apply for open-source discount.

**Release v5.4.0**
You can find the changes from version 5.4.0 at https://github.com/shiftcode/dynamo-easy/releases/tag/v5.4.0. Most of the changes targeted better typing and we added projection expression.
Hope that helps.

**Comment by VuongN** [comment]
I think it's better to get on the path of Docs/PR closer to the codes and host it via github pages. Let me think about it for a bit and see.
Thanks for the release notes link.

**Comment by VuongN** [comment]
Can we use something like [docpress](https://docpress.github.io/index.html) to replace the gitbook part at least? We'll have the Markdown doc files right in the git repos.

**Comment by michaelwittwer** [comment]
I would love to be closer to the source code with the docs. Right now I don't feel confident with just switching to the next easiest thing without elaborating on a few different implementation solutions. I let you know when we are there. Maybe you already did some research and have some pros & cons to share?

**Comment by michaelwittwer** [comment]
replacing this by #374 which collects open topics to be included in the docs and elaborates on the path forward.
