### ISSUE TITLE
Reduce lodash use

### ISSUE THREAD

**Issue by Tirke** [shiftcode/dynamo-easy#257]
**Is your feature request related to a problem? Please describe.**
Lodash is quite an heavy package and having to provide the full package for dynamo-easy to work is not ideal (especially in a AWS Lambda env).

**Describe the solution you'd like**
Remove all lodash calls

**Describe alternatives you've considered**
Use only lodash.x packages and never the full lodash package.

**Comment by michaelwittwer** [comment]
I am totally with you on that one. We don't use lodash anymore for internal projects because of the overhead and bad tree-shaking capabilities. (though i am more concerned about browser deliverables compared to lambda, where it's less critical).

This is a full list of used lodash methods and possible replacements:
- kebabCase (https://anguscroll.com/just/just-kebab-case)
- curry (https://anguscroll.com/just/just-curry-it)
- isPlainObject ({}.toString.call(value) === '[object Object]')
- has (only used in .spec, either write a helper function copied from lodash or rewrite assertions with [just-safe-get](https://anguscroll.com/just/just-safe-get))
- isEmpty (`Object.keys({a:'a',b:'a'} || {}).length`)
- isString (use native typeof value === 'string')
- isNumber (use native typeof value === 'number')

I like this util library a lot -> https://github.com/angus-c/just/. The only bad thing is that we need to fallback to the definitelyTyped repo for typings, and there are still most of the typings missing for this library.
