### ISSUE TITLE
DAX support

### ISSUE THREAD

**Issue by joeyhotz** [shiftcode/dynamo-easy#305]
Do you allow users to modify the dynamodb client used by dynamo easy? I want to be open to using DAX in the future and I'm not sure if this is supported from looking at the docs.

**Comment by ali-habibzadeh** [comment]
Ideal `updateDynamoEasyConfig` would have an additional field where we can pass client into and since Dax and Dynamodb have the same api, it shouldn't cause architecture change for dynamo-easy, besides abstracting out the underlying client used. Currently they are hardcoded inside dynamo services like `import * as DynamoDB from 'aws-sdk/clients/dynamodb'`

**Comment by simonmumenthaler** [comment]
hi @joeyhotz @ali-habibzadeh 
I never worked with the DAX client - but:
The `DynamoStore` constructor takes as the second argument an optional DynamoDB client instance. So _if_ the API from DAX _is_ compatible it _should_ already work. (Also every non-store request class (eg. `BatchGetRequest`) accepts an optional dynamoDB client)

I'd be nice if you could evaluate this :)

**Comment by itsdarrylnorris** [comment]
Hey @joeyhotz,

Any luck running DAX? I am considering using DAX on a project that I am working on right now.

**Comment by joeyhotz** [comment]
Hey all, sorry I've moved on to use postgres because dynamo didn't really
suit my use case and hence didn't get a chance to test out dynamo-easy with
a DAX client.

**Comment by michaelwittwer** [comment]
closing this in favour of #374 holding relevant topics to be updated in the docs, serving as a knowledge base for now and also describing the strategy of the technical solution of the documentation part, envision it to be closer to the source code of the project
